{
    "code": "FRA_LINK_BASE_GENERIC", 
    "logs": [
        "Traceback (most recent call last):", 
        "", 
        "  File \"freedomrobotics/link_base.py\", line 557, in freedomrobotics.link_base.LinkUploader.__loop_connection_check_to_freedom_api", 
        "", 
        "Exception: Token or secret not valid for this device: Account: AA2E4916C77670BAA7DA84BD4 Device: D7530172466E9EC156991C77C54 Token: T2F1C0BE7ED6A0B7D4FFE7DDE", 
        ""
    ], 
    "level": "fatal", 
    "errorMessage": "Unhandled exception in Link `agent_link` freedom api connection check loop: <type 'exceptions.Exception'> Token or secret not valid for this device: Account: AA2E4916C77670BAA7DA84BD4 Device: D7530172466E9EC156991C77C54 Token: T2F1C0BE7ED6A0B7D4FFE7DDE", 
    "component": "agent", 
    "attributes": {
        "python": {
            "implementation": "CPython", 
            "version": "2.7.17", 
            "build": [
                "default", 
                "Feb 27 2021 15:10:58"
            ]
        }, 
        "thread": {
            "daemon": false, 
            "name": "freedom_agent_link_connection_check_thread"
        }, 
        "geo": "Could not get geographic details: HTTPConnectionPool(host='ipinfo.io', port=80): Max retries exceeded with url: /json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff9d1c0e50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))", 
        "system": {
            "linux_dist": [
                "Ubuntu", 
                "18.04", 
                "bionic"
            ], 
            "ip": "Could not get ip: HTTPConnectionPool(host='ip.42.pl', port=80): Max retries exceeded with url: /raw (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff9d1c03d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))", 
            "user": "ubuntu", 
            "arch": "Unknown: aarch64", 
            "service": "systemd", 
            "hostname": "ubuntu", 
            "environment": {
                "LANG": "C.UTF-8", 
                "SHELL": "/bin/bash", 
                "JOURNAL_STREAM": "9:41721", 
                "LOGNAME": "ubuntu", 
                "USER": "ubuntu", 
                "PATH": "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin", 
                "HOME": "/home/ubuntu", 
                "INVOCATION_ID": "441b883101f847dd8e960798c33dfaca"
            }, 
            "platform": "Linux-5.4.0-1032-raspi-aarch64-with-Ubuntu-18.04-bionic", 
            "version": "#35~18.04.1-Ubuntu SMP PREEMPT Mon Mar 22 13:12:55 UTC 2021", 
            "release": "5.4.0-1032-raspi", 
            "docker": false, 
            "os": "Linux", 
            "processor": "aarch64"
        }, 
        "freedom_robotics": {
            "device": "D7530172466E9EC156991C77C54", 
            "freedom_python_module_version": "0.1.154", 
            "token": "***4FFE7DDE", 
            "account": "AA2E4916C77670BAA7DA84BD4", 
            "code_branch": "release"
        }
    }
}